name: Rust

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
#on:
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            build-tool: cargo-zigbuild
          - target: aarch64-apple-darwin
            os: macos-latest
            build-tool: cargo
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jira_branches
          archive: jira_branches-$target
          token: ${{ secrets.GITHUB_TOKEN }}
