name: Rust

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/aarch64-apple-darwin/jb
  build-platforms:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jira_branches
          archive: jira_branches-$target
          token: ${{ secrets.GITHUB_TOKEN }}
