name: Rust

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip release files
        shell: bash
        run:
          gzip -c bin/jb-aarch64-apple-darwin > bin/jb-aarch64-apple-darwin.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/jb-aarch64-apple-darwin.gz
  build-platforms:
    needs: create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jb
          archive: jb-$target
          token: ${{ secrets.GITHUB_TOKEN }}
